from typing import Any, Optional
from tbcml.core import io, game_version, country_code, mods


class FridaScript:
    def __init__(
        self,
        arc: str,
        cc: "country_code.CountryCode",
        gv: "game_version.GameVersion",
        script: str,
        name: str,
        mod: "mods.bc_mod.Mod",
    ):
        self.arc = arc
        self.cc = cc
        self.gv = gv
        self.script = script
        self.name = name
        self.mod = mod

    @staticmethod
    def get_file_path(arc: str, name: str) -> "io.path.Path":
        return io.path.Path(f"scripts/{arc}/{name}.json")

    def add_to_zip(self, zip: "io.zip.Zip"):
        json_data = self.serialize()
        json_file = io.json_file.JsonFile.from_object(json_data)
        zip.add_file(
            self.get_file_path(self.arc, self.name),
            json_file.to_data(),
        )

    def serialize(self) -> dict[str, Any]:
        return {
            "arc": self.arc,
            "cc": self.cc.get_code(),
            "gv": self.gv.to_string(),
            "script": self.script,
            "name": self.name,
        }

    @staticmethod
    def deserialize(data: dict[str, Any], mod: "mods.bc_mod.Mod") -> "FridaScript":
        return FridaScript(
            data["arc"],
            country_code.CountryCode.from_code(data["cc"]),
            game_version.GameVersion.from_string(data["gv"]),
            data["script"],
            data["name"],
            mod,
        )

    @staticmethod
    def from_zip(
        zip: "io.zip.Zip",
        mod: "mods.bc_mod.Mod",
        arc: str,
        name: str,
    ) -> "FridaScript":
        file = zip.get_file(FridaScript.get_file_path(arc, name))
        if file is None:
            raise ValueError("File not found in zip.")
        json_file = io.json_file.JsonFile.from_data(file)
        return FridaScript.deserialize(json_file.get_json(), mod)


class Scripts:
    def __init__(
        self,
        scripts: list["FridaScript"],
    ):
        self.scripts = scripts

    def is_valid_script(
        self,
        script: "FridaScript",
        cc: "country_code.CountryCode",
        gv: "game_version.GameVersion",
    ) -> bool:
        return script.cc == cc and script.gv == gv

    def validate_scripts(
        self, cc: "country_code.CountryCode", gv: "game_version.GameVersion"
    ):
        new_scripts: list["FridaScript"] = []
        for script in self.scripts:
            if self.is_valid_script(script, cc, gv):
                new_scripts.append(script)
        self.scripts = new_scripts

    def add_script(self, script: "FridaScript"):
        self.scripts.append(script)

    def remove_script(self, script: "FridaScript"):
        if script in self.scripts:
            self.scripts.remove(script)

    def get_script(self, arc: str) -> Optional["FridaScript"]:
        for script in self.scripts:
            if script.arc == arc:
                return script
        return None

    def add_scripts(self, scripts: "Scripts"):
        added_script = False
        for script in scripts.scripts:
            self.add_script(script)
            added_script = True
        return added_script

    def get_base_script(self):
        return """'use strict';

// This part of the script is automatically generated by tbcml.
// Log functions are provided for convenience.
// You can see the log by running adb logcat -s tbcml.

function logError(message) {
    Java.perform(function () {
        var Log = Java.use("android.util.Log");
        Log.e("tbcml", message);
        console.error(message);
    });
}
function logWarning(message) {
    Java.perform(function () {
        var Log = Java.use("android.util.Log");
        Log.w("tbcml", message);
        console.warn(message);
    });
}
function logInfo(message) {
    Java.perform(function () {
        var Log = Java.use("android.util.Log");
        Log.i("tbcml", message);
        console.info(message);
    });
}
function logVerbose(message) {
    Java.perform(function () {
        var Log = Java.use("android.util.Log");
        Log.v("tbcml", message);
        console.log(message);
    });
}
function logDebug(message) {
    Java.perform(function () {
        var Log = Java.use("android.util.Log");
        Log.d("tbcml", message);
        console.log(message);
    });
}
function log(message, level = "info") {
    switch (level) {
        case "error":
            logError(message);
            break;
        case "warning":
            logWarning(message);
            break;
        case "info":
            logInfo(message);
            break;
        case "verbose":
            logVerbose(message);
            break;
        case "debug":
            logDebug(message);
            break;
        default:
            logInfo(message);
            break;
    }
}

log("Script loaded successfully.");

function getBaseAddress() {
    return Module.findBaseAddress("libnative-lib.so").add(4096); // offset due to libgadget being added
}

function readStdString(address) {
    const isTiny = (address.readU8() & 1) === 0;
    if (isTiny) {
        return address.add(1).readUtf8String();
    }

    return address.add(2 * Process.pointerSize).readUtf8String();
}

// Mod scripts goes here.
"""

    def combine_scripts(self, arc: str) -> "io.data.Data":
        script_text = self.get_base_script() + "\r\n"
        for script in self.scripts:
            if script.arc == arc:
                script_text += f"// {'-'*50}\r\n// {script.name} from mod {script.mod.name} by {script.mod.author}\r\n// {'-'*50}\r\n\r\n"
                script_text += script.script
        return io.data.Data(script_text)

    def add_to_zip(self, zip: "io.zip.Zip"):
        arcs: dict[str, list[str]] = {}
        for script in self.scripts:
            script.add_to_zip(zip)
            if script.arc not in arcs:
                arcs[script.arc] = []
            arcs[script.arc].append(script.name)
        json_data = {
            "arcs": arcs,
        }
        json = io.json_file.JsonFile.from_object(json_data)
        zip.add_file(io.path.Path("scripts/scripts.json"), json.to_data())

    @staticmethod
    def from_zip(
        zip: "io.zip.Zip",
        mod: "mods.bc_mod.Mod",
    ) -> "Scripts":
        file = zip.get_file(io.path.Path("scripts/scripts.json"))
        if file is None:
            raise ValueError("File not found in zip.")
        json = io.json_file.JsonFile.from_data(file)
        json_data = json.get_json()
        arcs = json_data["arcs"]
        scripts: list["FridaScript"] = []
        for arc in arcs:
            for name in arcs[arc]:
                scripts.append(FridaScript.from_zip(zip, mod, arc, name))
        return Scripts(scripts)

    def import_scripts(self, other: "Scripts"):
        for script in other.scripts:
            self.add_script(script)

    def get_used_arcs(self) -> list[str]:
        arcs: set[str] = set()
        for script in self.scripts:
            arcs.add(script.arc)
        return list(arcs)
